########################################################################
# This is the development Docker file                                  #
#                                                                      #
# It overrides the base file with development setup; specifically it:  #
#   - runs the Flask development server                                #
#   - creates a container to run npm in (for the front end; disabled)  #
########################################################################

version: "3.7"
services:
    flask:
        command: python app.py
        ports:
            - 5000:5000
    # NOTE: npm has performance issues inside Docker
    #       therefore, best to run outside Docker (for now)
    # frontend:
    #     image: node:14.11.0-alpine3.12
    #     tty: true                  # keep it running
    #     ports:
    #         - 3000:3000
    #     volumes:
    #         - ./client:/var/www
    #     working_dir: /var/www
    #     command: npm start
    #     environment: 
    #         CHOKIDAR_USEPOLLING: "true"