version: '3.7'

services:
  server:
    build: 
      context: ./
      dockerfile: ./server/Dockerfile
    command: python app.py
    ports:
      - 5001:5000
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
      - IS_DOCKER=1
  
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cradle
      
volumes:
  mysql_data: