version: '3.7'

services:
  server:
    build: ./server
    command: python app.py
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
      - IS_DOCKER=1