version: '3.7'

services:
  server:
    build: 
      context: ./
      dockerfile: ./server/Dockerfile.prod
    command: ./prod/wait-for.sh gunicorn -c ./prod/gunicorn.conf.py app:app
    volumes: 
      - cradle_logs:/var/log
    expose:
      - 5000
    env_file:
      - ./server/.env.prod
    environment:
      - PORT=5000
    container_name: cradle
    depends_on: 
      - db

  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    env_file: 
      - ./server/.env.prod.db
    container_name: mysql

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    depends_on:
        - server
    volumes:
        - ./client/build:/usr/share/nginx/html
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80
        - 443:443
      
volumes:
  mysql_data:
  cradle_logs: