version: "3.8"
services:
    caddy:
        container_name: caddy
        image: caddy:2.0.0
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
        ports:
            - 80:80
            - 443:443
        environment:
            CADDY_DOMAIN: ${CADDY_DOMAIN}
    flask:
        container_name: flask
        build:
            context: ./server
        command: python app.py    # development
        # command: gunicorn -c ./prod/gunicorn.conf.py app:app    # production
        volumes:
            - ./server:/usr/src/server
        environment:
            PORT: 5000
            DB_HOSTNAME: mysql
            DB_PORT: 3306
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
    mysql_data: