version: '3.7'

services:
  client: 
    container_name: client
    build: ./client
    command: yarn start
    ports: 
      - 3000:3000
    volumes:
      - './client:/usr/src/client'
      - '/usr/src/client/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: 
      context: ./
      dockerfile: ./server/Dockerfile
    command: python app.py
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
    container_name: cradle
    volumes:
      - ./server:/usr/src/server
      - ./client:/usr/src/client
    depends_on: 
      - db

  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    container_name: mysql
      
volumes:
  mysql_data: