###################################################
# This is the production Docker file              #
#                                                 #
# It includes the following containers:           #
#  - Caddy                                        #
#  - Flask (extended, running using prod server)  #
#  - MySQL (extended)                             #
###################################################

version: "3.8"
services:
    flask:
        command: gunicorn -c ./prod/gunicorn.conf.py app:app
    caddy:
        image: caddy:2.0.0
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
        ports:
            - 80:80
            - 443:443
        environment:
            CADDY_DOMAIN: ${CADDY_DOMAIN}

volumes:
    mysql_data: