version: '3.7'

services:
  server:
    build: 
      context: ./
      dockerfile: ./server/Dockerfile
    command: gunicorn -c gunicorn.conf.py app:app
    volumes: 
      - cradle_logs:/var/log
    ports:
      - 5001:5000
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
    container_name: cradle
    depends_on: 
      - db

  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cradle
    container_name: mysql
      
volumes:
  mysql_data:
  cradle_logs: